@startuml
!include https://raw.githubusercontent.com/patrik-csak/one-dark-plantuml-theme/v1.0.1/theme.puml
hide circle
skinparam {
    classAttributeIconSize 0
    packageStyle rectangle
    backgroundColor transparent
}  

class Mensch {
    + Mensch(Hund hund)
    + double getX()
    + double getY()
    + void gassiGehen()
    + void hundRufen()
}

class Hund {
    + Hund()
    + double getX()
    + double getY()
    + void beiFuss(Mensch herrchen)
    + void zuPositionLaufen(double x, double y)
}

class Group {
    + Group()
    + void add(Shape shape)
    + void move(double dx, double dy)
}

Mensch --> Hund : -meinHund
Mensch --> Group : -grafikGruppe
Hund --> Group : -group
@enduml